"""empty message

Revision ID: 4cef1801ea30
Revises: 
Create Date: 2020-04-10 10:58:18.204790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cef1801ea30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ages'))
    )
    op.create_table('alembic_api',
    sa.Column('version_num', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('pk_alembic_api'))
    )
    op.create_table('countries',
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('country_code', name=op.f('pk_countries')),
    sa.UniqueConstraint('country_name', name=op.f('uq_countries_country_name'))
    )
    op.create_table('dates',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('epoch', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('quarter_month_day', sa.Integer(), nullable=False),
    sa.Column('month_day', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(), nullable=False),
    sa.Column('month_abbrev', sa.String(), nullable=False),
    sa.Column('weekday_name', sa.String(), nullable=False),
    sa.Column('weekday_abbrev', sa.String(), nullable=False),
    sa.Column('week_in_month', sa.Integer(), nullable=False),
    sa.Column('week_in_year', sa.Integer(), nullable=False),
    sa.Column('day_in_week', sa.Integer(), nullable=False),
    sa.Column('day_in_year', sa.Integer(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('year_in_dimension', sa.Integer(), nullable=False),
    sa.Column('month_in_dimension', sa.Integer(), nullable=False),
    sa.Column('day_in_dimension', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week_in_year', sa.Integer(), nullable=False),
    sa.Column('iso_day_in_year', sa.Integer(), nullable=False),
    sa.Column('iso_day_in_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dates')),
    sa.UniqueConstraint('date', name=op.f('uq_dates_date'))
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests')),
    sa.UniqueConstraint('name', name=op.f('uq_interests_name'))
    )
    op.create_table('times',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False),
    sa.Column('hourap', sa.SmallInteger(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('minute_of_day', sa.Integer(), nullable=False),
    sa.Column('second_of_day', sa.Integer(), nullable=False),
    sa.Column('quarter_hour', sa.String(), nullable=False),
    sa.Column('am_pm', sa.String(), nullable=False),
    sa.Column('day_night', sa.String(), nullable=False),
    sa.Column('day_night_abbrev', sa.String(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('time_period_abbrev', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_times')),
    sa.UniqueConstraint('time', name=op.f('uq_times_time'))
    )
    op.create_table('cities',
    sa.Column('city_code', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], name=op.f('fk_cities_country_code')),
    sa.PrimaryKeyConstraint('city_code', name=op.f('pk_cities'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('id_str', sa.String(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_background_image_url', sa.Text(), nullable=True),
    sa.Column('profile_background_image_url_https', sa.Text(), nullable=True),
    sa.Column('profile_banner_url', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('profile_image_url_https', sa.Text(), nullable=True),
    sa.Column('profile_background_tile', sa.BOOLEAN(), nullable=True),
    sa.Column('profile_use_background_image', sa.BOOLEAN(), nullable=True),
    sa.Column('default_profile', sa.BOOLEAN(), nullable=True),
    sa.Column('default_profile_image', sa.BOOLEAN(), nullable=True),
    sa.Column('protected', sa.BOOLEAN(), nullable=True),
    sa.Column('following', sa.BOOLEAN(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('contributors_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('geo_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('has_extended_profile', sa.BOOLEAN(), nullable=True),
    sa.Column('is_translation_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_translator', sa.BOOLEAN(), nullable=True),
    sa.Column('translator_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('city_code', sa.String(), nullable=True),
    sa.Column('birthyear', sa.SmallInteger(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ag_ai_version', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('entities_display_url', sa.String(), nullable=True),
    sa.Column('entities_expanded_url', sa.Text(), nullable=True),
    sa.Column('entities_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_code'], ['cities.city_code'], name=op.f('fk_users_city_code')),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], name=op.f('fk_users_country_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('screen_name', name=op.f('uq_users_screen_name'))
    )
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_city_code'), 'users', ['city_code'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_protected'), 'users', ['protected'], unique=False)
    op.create_table('fan_demo_ages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['ages.id'], name=op.f('fk_fan_demo_ages_age_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fan_demo_ages_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'age_id', name=op.f('pk_fan_demo_ages'))
    )
    op.create_table('fan_demo_cities',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city_code', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_code'], ['cities.city_code'], name=op.f('fk_fan_demo_cities_city_code')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fan_demo_cities_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'city_code', name=op.f('pk_fan_demo_cities'))
    )
    op.create_table('fan_demo_countries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], name=op.f('fk_fan_demo_countries_country_code')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fan_demo_countries_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'country_code', name=op.f('pk_fan_demo_countries'))
    )
    op.create_table('fan_demo_genders',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('males_count', sa.Integer(), nullable=False),
    sa.Column('females_count', sa.Integer(), nullable=False),
    sa.Column('null_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fan_demo_genders_user_id')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_fan_demo_genders'))
    )
    op.create_table('fan_demo_interests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_fan_demo_interests_interest_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fan_demo_interests_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'interest_id', name=op.f('pk_fan_demo_interests'))
    )
    op.create_table('fans',
    sa.Column('followed_id', sa.BigInteger(), nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_fans_followed_id')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_fans_follower_id')),
    sa.PrimaryKeyConstraint('followed_id', 'follower_id', name=op.f('pk_fans'))
    )
    op.create_table('kols',
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('crawled_profile', sa.BOOLEAN(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fans_ids_count', sa.Integer(), nullable=True),
    sa.Column('fans_ids_last_crawled', sa.DateTime(), nullable=True),
    sa.Column('fans_profiles_count', sa.Integer(), nullable=True),
    sa.Column('fans_profiles_last_crawled', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_kols_id')),
    sa.PrimaryKeyConstraint('screen_name', name=op.f('pk_kols')),
    sa.UniqueConstraint('id', name=op.f('uq_kols_id'))
    )
    op.create_table('user_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('listed_count', sa.Integer(), nullable=False),
    sa.Column('favourites_count', sa.BigInteger(), nullable=False),
    sa.Column('statuses_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], name=op.f('fk_user_stats_date_id')),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_user_stats_id')),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], name=op.f('fk_user_stats_time_id')),
    sa.PrimaryKeyConstraint('id', 'date_id', 'time_id', name=op.f('pk_user_stats'))
    )
    op.create_table('users_interests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_users_interests_interest_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_interests_user_id')),
    sa.PrimaryKeyConstraint('user_id', 'interest_id', name=op.f('pk_users_interests'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_interests')
    op.drop_table('user_stats')
    op.drop_table('kols')
    op.drop_table('fans')
    op.drop_table('fan_demo_interests')
    op.drop_table('fan_demo_genders')
    op.drop_table('fan_demo_countries')
    op.drop_table('fan_demo_cities')
    op.drop_table('fan_demo_ages')
    op.drop_index(op.f('ix_users_protected'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_city_code'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_table('users')
    op.drop_table('cities')
    op.drop_table('times')
    op.drop_table('interests')
    op.drop_table('dates')
    op.drop_table('countries')
    op.drop_table('alembic_api')
    op.drop_table('ages')
    # ### end Alembic commands ###
